In [1]:
import pandas as pd
import numpy as np

In [17]:
dataset=pd.read_csv('winequality-red.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=0)

In [19]:
print(x_train)

[[ 9.9   0.54  0.45 ...  3.39  0.62  9.4 ]
 [10.8   0.26  0.45 ...  3.13  0.54  9.6 ]
 [ 9.9   0.35  0.55 ...  3.26  0.79 10.6 ]
 ...
 [ 7.9   0.57  0.31 ...  3.29  0.69  9.5 ]
 [13.    0.47  0.49 ...  3.3   0.68 12.7 ]
 [ 9.8   0.98  0.32 ...  3.25  0.48  9.4 ]]


In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [69]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors = 100, weights='distance', algorithm = 'kd_tree', metric = 'manhattan', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', metric='manhattan', n_neighbors=100,
                     weights='distance')

In [70]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6 6]
 [5 5]
 [7 7]
 [5 6]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [5 4]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 5]
 [6 6]
 [6 6]
 [7 7]
 [6 5]
 [6 5]
 [5 4]
 [6 7]
 [5 6]
 [6 6]
 [6 4]
 [6 6]
 [5 5]
 [5 5]
 [6 7]
 [5 5]
 [6 6]
 [6 5]
 [6 6]
 [6 5]
 [5 6]
 [7 7]
 [7 7]
 [5 5]
 [6 6]
 [6 6]
 [6 7]
 [5 5]
 [6 7]
 [6 6]
 [6 6]
 [6 5]
 [5 5]
 [5 6]
 [6 6]
 [5 6]
 [6 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 6]
 [5 5]
 [5 5]
 [5 5]
 [7 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 6]
 [5 6]
 [5 4]
 [5 6]
 [6 5]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 5]
 [5 5]
 [5 5]
 [6 6]
 [6 4]
 [5 5]
 [6 7]
 [5 6]
 [6 6]
 [5 5]
 [5 6]
 [6 5]
 [7 8]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 5]
 [6 7]
 [5 5]
 [6 6]
 [5 5]
 [6 7]
 [5 5]
 [6 6]
 [6 6]
 [5 6]
 [7 7]
 [6 6]
 [6 6]
 [5 5]
 [6 7]
 [5 5]
 [5 5]
 [6 6]
 [7 6]
 [5 5]
 [5 5]
 [6 5]
 [6 6]
 [5 6]
 [5 6]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 8]
 [5 5]
 [6 6]
 [5 5]
 [5 6]

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[  0   0   2   0   0   0]
 [  0   0   7   4   0   0]
 [  0   0 108  26   1   0]
 [  0   0  30 108   4   0]
 [  0   0   1  15  11   0]
 [  0   0   0   1   2   0]]
0.709375
